server:
  port: 8080
spring:
  profiles:
    active: dev
  application:
    name: api-gateway
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

springdoc:
  swagger-ui:
    urls:
      - name: user-service
        url: /user/v3/api-docs
      - name: product-service
        url: /product/v3/api-docs
      - name: order-service
        url: /order/v3/api-docs
      - name: cart-service
        url: /cart/v3/api-docs
      - name: notification-service
        url: /notification/v3/api-docs
