spring:
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: 55855f1c92e133
    password: b7c8c851e92dbe
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
