spring:
  mail:
    host: ${MAIL_HOST:sandbox.smtp.mailtrap.io}
    port: ${MAIL_PORT:2525}
    username: ${MAIL_USERNAME:55855f1c92e133}
    password: ${MAIL_PASSWORD:b7c8c851e92dbe}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}
